### PR TITLE
Includepaths

### LINKED ISSUE #21: Add option to specify include paths
In `compiler_ly` there is already the notion of LilyPond's `-I` command line option, but it only makes use of the file path of the LilyPond file's directory.

There should be the possibility to specify a *list* of include paths, probably on a document-wide level (I'm not sure if it's necessary to change them along the way or even locally).

So the `compiler_ly` function should be modified to iterate over the include argument as a list, such a list has to be made available as a variable in the Lua file, and there should be a macro to set/define this list.

In addition I suggest to also add the directory of the *LaTeX* file to the include directories because it may be an option for many use cases to have include files in *that* directory. This should also be added to the command line when compiling *fragments*.

### PR DESCRIPTION
**Pull request by jperon**
This PR is based on #41, which should be reviewed and merged first.
It should fix #21 and #33.

### CODE REVIEW

**Comment by uliska** [comment]
I must admit it is too late now to really dig through the code tonight, but I have two comments so far:

1)
Is it OK to require "no spaces around the comma"? OK, in the TeX world people are probably used to that kind of rules, but in general I think we could offer something more permissive. Shouldn't be  too hard.

2)
The include paths should not necessarily be relative to the current directory. Actually this would be the exception rather than the rule. The idea about the include paths is not to shorten the actual include commands but to allow the inclusion of files that can *not* be found relative, for example library files.
I'm not sure if it's necessary to actually integrate files that are included through an absolute include path in the hash consideration (this may include large amounts of rather static library code), but maybe behaviour should be consistent between the flatten function and the code in `run_lilypond()`.

**Comment by jperon** [comment]
It should now be possible to use absolute paths, and a space after the comma is allowed.

There is only one drawback : I don't know why, but the `--include` argument of LilyPond doesn't seem to accept relative paths. So relative paths have to be preceded by `./`, and `lyluatex.sty` replaces it with the full path of current directory.

**Comment by uliska** [comment]
> the --include argument of LilyPond doesn't seem to accept relative paths

Ah really? I'll have to test that.
Your solution seems sound, though, and I'll review ASAP this afternoon.

**Comment by jperon** [comment]
A question that would need to be investigated is the compatibility of all that with Windows ; but I think this shouldn't block merge for now, and could be seen later.

**Comment by uliska** [comment]
Yes, we should do our best to support Windows equally (although personally I don't care about that). But recent investigations with openLilyLib indicate that this isn't too hard since LilyPond seems to convert everything to forward slashes and works well with that (the only notable difference being Windows' volume letter vs. Unix's root directory.

**Comment by jperon** [comment]
That's funny : when I try it from the lua code (removing the `lfs.currentdir()` stuff), this doesn't work. Never mind, as is, it's possible to specify either absolute or relative (with `./`) paths, so let's merge.

**Pull request merged**
