### PR TITLE
Let the user define his own `verbatim` environment

### PR DESCRIPTION
**Pull request by jperon**
Following @rpspringuel's suggestion about #104.

### CODE REVIEW

**Comment by uliska** [comment]
Works correctly, but I'm not 100% happy with the interface. Asking the user to actually pass LaTeX code to a macro seems somewhat inconsistent with our usual behaviour.
I'd prefer something like
```tex
\lyhighlighting[language=TeX]{lstlisting}{listings}
```
that will generate the environment *and* load the package in one step.

**Comment by jperon** [comment]
The problem with such an approach would be that only an environment could be used. Perhaps someone could want to use a command before and a command after, not necessarily an environment.

**Comment by jperon** [comment]
The logic in `\lysetverbenv` is the same as `\newenvironment`, so it shouldn't be difficult to understand for the user.

**Comment by uliska** [comment]
OK.

**Pull request merged**
