### PR TITLE
`cleantmp` option

### PR DESCRIPTION
**Pull request by jperon**
If `cleantmp=true` is given as a package option, the temporary files (within `tmp_ly`)
that aren't listed in `jobname.list` will be deleted.

### CODE REVIEW

**Comment by jperon** [comment]
This should fix #24.

**Comment by uliska** [comment]
I think we should not read `FILELIST` but all `*.list` files found in the temp directory.
If we have two tex files in our directory (which share the temp directory) we don't want to remove the legitimate scores from the other document. Or am I missing something?

**Comment by jperon** [comment]
Here you are ; I think it should be ready for merge.

**Comment by jperon** [comment]
Merging now to avoid conflicts when working on #29 and #46. Feel free to open an issue if you see anything bad.

**Comment by uliska** [comment]
Everything seems to work fine (had to scratch my hair a lot until finding out that I should actually *use the option* to test the code ;-)

**Pull request merged**
