### PR TITLE
support MiKTeX with LilyPond ≤ 2.22

### PR DESCRIPTION
**Pull request by szollbrecht**
These changes made it work for me on windows 11 with miktex, running lualatex from the console or texniccenter.

It's more a workaround than a proper solution but maybe it helps you finding the issue with miktex or someone else in the meantime.

### CODE REVIEW

**Comment by jperon** [comment]
I intended to try it yesterday, so I launched a Windows 10 VM, and tried to install MiKTeX. But when I see how it works on my first MWE and [how the main author handles issues](https://github.com/MiKTeX/miktex/issues/1249#issuecomment-1357247758), I suddenly feel less motivated…

**Comment by jperon** [comment]
After eventually finding a way to have MiKTeX run (my Windows 10 had to be updated), I have checked that this fix is working *with lilypond 2.22*. With 2.24, there is another problem (seems a problem with pdf version) that I can’t reproduce on TeXLive/Linux. As I said, having experimented the way issues are handled from MiKTeX, I feel no motivation to tell about this problem upstream; feel free if you want to.

So I’ll merge it as is, and add a documentation note about the incompatibility with 2.24.

**Comment by szollbrecht** [comment]
oh my, really not helpful at all... "works for me"🤦‍♂️
thanks anyway, maybe in the future when I have motivation again, I will check once more :)

**Comment by jperon** [comment]
@szollbrecht Thank you very much for having made the work!

**Pull request merged**
