### PR TITLE
Code linting

### PR DESCRIPTION
**Pull request by jperon**
For now, we have private functions, a `Score` class and a `ly` public table to expose lua functions to LaTeX commands. Private LaTeX commands are prefixed by `ly@`.
There are quite many things to do yet, but at least the `.sty` is cleaner, and functions in the `.lua` are in a better order.

### CODE REVIEW

**Comment by jperon** [comment]
I think #55 should be mostly fixed. Could you tell me what you think, please ?

**Comment by jperon** [comment]
The main purpose of this PR should be OK, I think. If you don't see any mistake, it should be merged; for new functions (error checking etc.), new issues could be opened.

**Comment by rpspringuel** [comment]
Not surprisingly the diffs aren't really informative for this kind of change.  I'm going to have to study the revised code before I can comment intelligently on it and I simply won't have time for that before next weekend (Feb 10 & 11).  If you guys are happy with it before then, don't let my lack of comment stop you from merging.

**Comment by uliska** [comment]
I have read through the code and tested a few of the exmaple files.

The `.sty` file looks very good. The `.lua` file too, but I must say I will need some time to get used to it, so I can't really comment on it. However, I suggest you merge it so we can base any new work on that.

Just one question:

```lua
function Score:set_roman_font()
end
```
in l.449/450, is that a remainder that should be purged or a stub for something to come?

**Pull request merged**
